spring:
  application:
    name: searcher
  data:
    mongodb:
      database: reverseindex
      host: localhost
      port: 27018

server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/