spring:
  application:
    name: apigateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

server:
  port: 8880

zuul:
  routes:
    text-service:
      path: /text-service/**
      serviceId: indexator
    search-service:
      path: /search-service/**
      serviceId: searcher