spring:
  application:
    name: storeoriginaldata
  data:
    mongodb:
      database: originaltext
      host: 192.168.2.166
      port: 27017

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.2.166:8762/eureka/


