spring:
  application:
    name: storeoriginaldata
  data:
    mongodb:
      database: originaltext
      host: localhost
      port: 27017

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/


